
website:
  title: "Your Name"
  favicon: img/favicon.ico
  navbar:
    brand:
      image: img/emory_logo.png
      href: index.qmd
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Contact"
        href: contact.qmd
  repo-url: https://github.com/fphng/academic-site

  
format:
  html:
    theme:
      light: united     # or any Bootswatch theme name
      dark: darkly
    css: styles.scss
    toc: true
    toc-depth: 2
    code-fold: true
    number-sections: true